Add CI
guardian/image-rendering pull request #19
Opened 2020-09-07 13:15 UTC by JamieB-gu

## Why?

To run validation checks against PRs and `main` branch merges. This workflow checks out the code, installs npm dependencies (with cache), and runs the `build`/`test` scripts. Based on GitHub's default Node.js workflow, and [the one](https://github.com/guardian/apps-rendering/blob/15773fa4d030f6d4b091b35bd5a5295414b3cb40/.github/workflows/nodejs.yml) currently used by apps-rendering.

## Changes

- New Node-based GH workflow to validate changes

2020-09-07 13:38 UTC, webb04 commented on .github/workflows/node.js.yml
> +        node-version: [10.x, 12.x]
Do we still need to run against node 10?

2020-09-08 07:57 UTC, mxdvl requested changes
Great idea!

I think a snapshot needs to be created locally and tracked for the CI tests to work. I think this can be done locally by adding the updating the `package.json` scripts:

```
"test": "jest tests --coverage --updateSnapshot"
```

From: https://github.com/facebook/jest/issues/9235#issuecomment-673459064

2020-09-08 13:52 UTC, JamieB-gu commented
> I think a snapshot needs to be created locally and tracked for the CI tests to work

That's true, but what's puzzling me is that [I've already done that](https://github.com/guardian/image-rendering/blob/main/src/__snapshots__/sizes.test.tsx.snap). The tests pass quite happily locally using those existing snapshot files.

I _could_ update the `test` script to use `--updateSnapshot` in the CI environment... but surely the only reason you'd _want_ to update snapshots would be to so that you could commit them to VC, which we _won't_ be doing in CI...

Like I said, I'm puzzled 🤔

2020-09-09 08:07 UTC, mxdvl approved these changes
`"testPathIgnorePatterns": ["dist"]` 👍

2020-09-09 09:33 UTC, merged